# 🚀 DiagramatIQ - Production Docker Compose for Dokploy
version: '3.8'

services:
  # 🦙 Ollama - IA Local (NECESARIO)
  ollama:
    image: ollama/ollama:latest
    container_name: diagramatiq-ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=${ALLOWED_ORIGINS:-*}
    networks:
      - diagramatiq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 🚀 Backend API (FastAPI)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: diagramatiq-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - OLLAMA_HOST=http://ollama:${OLLAMA_PORT:-11434}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-llama3.2:3b}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - diagramatiq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 🌐 Frontend (Next.js) - Production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diagramatiq-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_OLLAMA_HOST=${NEXT_PUBLIC_OLLAMA_HOST:-http://localhost:11434}
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST:-http://localhost:8080}
      - NEXT_PUBLIC_PERPLEXITY_API_KEY=${NEXT_PUBLIC_PERPLEXITY_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    networks:
      - diagramatiq-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# 📦 Volúmenes persistentes
volumes:
  ollama-data:
    driver: local

# 🌐 Red interna
networks:
  diagramatiq-network:
    driver: bridge